/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native */

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT void JNICALL Java_Native_sum
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
